// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Artist struct {
	ArtistID   int64  `json:"artist_id"`
	ArtistName string `json:"artist_name"`
}

type Song struct {
	SongID          int64  `json:"song_id"`
	SongName        string `json:"song_name"`
	ArtistID        int64  `json:"artist_id"`
	ArtistName      string `json:"artist_name"`
	ThumbnailS3Path string `json:"thumbnail_s3_path"`
	Mp3S3Path       string `json:"mp3_s3_path"`
}

type User struct {
	UserID      int64        `json:"user_id"`
	UserName    string       `json:"user_name"`
	FirstName   string       `json:"first_name"`
	LastName    string       `json:"last_name"`
	DataOfBirth sql.NullTime `json:"data_of_birth"`
	LastLogin   sql.NullTime `json:"last_login"`
	CreatedAt   sql.NullTime `json:"created_at"`
}
