// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateArtist(ctx context.Context, artistName string) (Artist, error)
	CreateSong(ctx context.Context, arg CreateSongParams) (Song, error)
	DeleteArtist(ctx context.Context, artistID int64) error
	DeleteSong(ctx context.Context, songID int64) error
	GetArtist(ctx context.Context, artistID int64) (Artist, error)
	GetSong(ctx context.Context, songID int64) (Song, error)
	ListArtists(ctx context.Context, limit int32) ([]Artist, error)
	ListSongs(ctx context.Context, limit int32) ([]Song, error)
	UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error)
	UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error)
}

var _ Querier = (*Queries)(nil)
